---
AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM User"

Parameters:
  UserName:
    Type: String
    Default: ""
    Description: Name of the IAM user

  S3BucketName:
    Type: String
    Default: ""
    Description: Name of the S3 Bucket on which your IAM user needs access.


Resources:
  IamUserManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
         -
           Effect: "Allow"
           Action:
             - "s3:DeleteObject"
             - "s3:DeleteObjectVersion"
             - "s3:PutObject"
             - "s3:GetObject"
             - "s3:GetObjectVersion"
             - "s3:RestoreObject"
             - "s3:ListBucket"
             - "s3:ListBucketVersions"
           Resource: [
             !Sub 'arn:aws:s3:::${S3BucketName}',
             !Sub 'arn:aws:s3:::${S3BucketName}/*',
           ]
         -
           Effect: "Allow"
           Action:
             - "s3:ListAllMyBuckets"
           Resource: "*"

  IamUser:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - !Ref IamUserManagedPolicy
      UserName: !Ref UserName