---
AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Bucket"

Parameters:
  S3BucketName:
    Type: String
    Default: ""
    Description: Name of the S3 Bucket


Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 2
          ExpiredObjectDeleteMarker: true
          Id: cleanup
          NoncurrentVersionExpiration:
            NoncurrentDays: 1
          Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
